//Summarizes all the classes for the background, such as sea grass, landscapes, etc.
//Makes the draw function in the main tab look more clean

class BackGround {
  seaPlant[] seaGrass = new seaPlant[200];  //make a field of grass
  Anemone[] anemone = new Anemone[15];  //make anemone
  landscape rocks1; 
  landscape rocks2;
  landscape rocks3;

  PImage ocean;

  BackGround() {
    ocean = loadImage("ocean.jpg");

    rocks1 = new landscape(700, 800, #496575);  //closest to farthest
    rocks2 = new landscape(500, 700, #003a5c);
    rocks3 = new landscape(600, 400, #002135);  

    for (int i = 0; i < seaGrass.length; i++) {                                  //Make an array of sea grass at this location
      seaGrass[i] = new seaPlant(new PVector(random(5, width-5), height));
    }

    for (int j = 0; j < anemone.length; j++) {                                   //Make an array of anemone at this location
      anemone[j] = new Anemone(new PVector(random(100, 300), height));
    }
  }

  void display() {
    image(ocean, 0, 0);         //Blue background
    rocks3.display();           //Underwater Landscapes generated by perlin noise
    rocks2.display();
    rocks1.display();

    for (int i = 0; i < seaGrass.length; i++) {           //Run functions for display, update etc. for the sea grass and the anemone
      seaGrass[i].run();
    }

    for (int j = 0; j < anemone.length; j++) {
      anemone[j].run();
    }
  }
}